### PR TITLE
Save QAction's as class variables

### PR DESCRIPTION
**Pull request by JamesWrigley**
This fixes segfaults that I came across locally. Presumably the actions were getting GC'd before the slots that use them were signalled.

### CODE REVIEW

**Comment by tmichela** [comment]
LGTM

**Review by tmichela — APPROVED** [review]

**Comment by JamesWrigley** [comment]
And apparently also introduces new segfaults...

**Comment by JamesWrigley** [comment]
Going off the logs I'd say it's some kind of race condition involving plotly/kaleido? Kaleido at least is what's appearing in the logs. So far it's consistently failing at `test_table_and_plotting` but that shouldn't touch any plotly stuff. Not really sure where the extra thread is coming from either.

Anyway, I think this PR is still an improvement so I'll merge it. I don't think it's the cause of the bug because the same failure happened once on #284.

**Comment by takluyver** [comment]
Thanks! I always get confused about when Qt does & doesn't keep objects alive.

> Not really sure where the extra thread is coming from either.

Looks like kaleido starts a thread internally as part of managing its subprocess: https://github.com/plotly/Kaleido/blob/056642fe8994354838a7cb619f6a98a7ad0608ab/repos/kaleido/py/kaleido/scopes/base.py#L185-L189

**Pull request merged**
