### PR TITLE
Fix migration with scalar coordinates from DataArrays

### PR DESCRIPTION
**Pull request by takluyver**
Tested on HED proposal 4520. Input structure:

```text
├K1
│ ├data   [uint16: 4096 × 4096]
│ └trainId        [uint64: ]
```

Output:

```text
├K1 (1 attributes)
│ ├__xarray_dataarray_variable__  [uint16: 4096 × 4096] (4 attributes)
│ ├dim_0  [float32: 4096] (4 attributes)
│ ├dim_1  [float32: 4096] (4 attributes)
│ └trainId        [uint64: ]
```

### CODE REVIEW

**Comment by JamesWrigley** [comment]
What happens to `trainId` when this is loaded into a DataArray?

**Comment by takluyver** [comment]
It recreates a DataArray with an additional coordinate not tied to a dimension:

```
In [3]: xr.load_dataarray('extracted_data/p4520_r832.h5', group='K1', engine='h5netcdf')
Out[3]: 
<xarray.DataArray (dim_0: 4096, dim_1: 4096)>
array([[ 121,  121,  122, ...,  125,  127,  116],
       [ 124,  112,  173, ...,  134,  123,  132],
       [ 135,  127,  118, ...,  132,  138,  136],
       ...,
       [ 147,  132,  135, ...,  129,  137,  140],
       [ 136,  145,  137, ...,  142,  143,  148],
       [ 144,  134,  141, ..., 2312,  777,  776]], dtype=uint16)
Coordinates:
    trainId  uint64 1826424101
Dimensions without coordinates: dim_0, dim_1
```

**Review by JamesWrigley — APPROVED** [review]
I assume this is ready to merge even though it's a draft :) LGTM!

**Comment by takluyver** [comment]
Thanks! Yes, I just keep forgetting to switch the 'open pull request' button back off draft mode.

**Pull request merged**
