### PR TITLE
Listen for incoming events on EuXFEL Kafka broker

### PR DESCRIPTION
**Pull request by takluyver**
We still need to know the new topic for migration events (topics are now namespaced).

Do we want to move over the internal updates as well? We're currently using the first test broker that was set up (exflwebstor01).

### CODE REVIEW

**Comment by tmichela** [comment]
> Do we want to move over the internal updates as well?

Probably since `exflwgs06` seems to be the production one, the one we use currently may also disappear and or not be up for support if something happened to it.

**Comment by takluyver** [comment]
Janusz M just sent me the new topic name for migrations, so I've updated that as well. This should be ready to go now.

**Review by JamesWrigley — APPROVED** [review]
LGTM! The readme docs will be out of date, but I'll fix that when I move them to the official docs.

**Comment by takluyver** [comment]
Aha, I hadn't spotted that, thanks! I've updated it now - it's easy to do, and it seems better to keep them in sync than you having to remember to do it.

**Pull request merged**
