### PR TITLE
Make per-run logs accessible from the GUI

### PR DESCRIPTION
**Pull request by takluyver**
The actual viewer is super simple for now - just a QPlainTextEdit in read-only mode. But as log files are now per-run, they're relatively small, so I think the ability to filter them is less important. I'm sure we'll want to add features at some point, but we can start simple.

Screenshot from 2023-11-08 14-54-29

Screenshot from 2023-11-08 14-54-52

### CODE REVIEW

**Comment by JamesWrigley** [comment]
What happens when you try to open this 17MB log file? `/gpfs/exfel/exp/MID/202304/p003422/usr/Shared/amore/slurm_logs/r162-p3422-1295446.out`

I'm mostly just curious, no worries if it's very slow since that's a rather extreme case :grin:

**Comment by takluyver** [comment]
I was expecting it to be terrible, but actually, it seemed to be perfectly fine, opening almost instantly and allowing me to scroll OK. I guess 17 MB just isn't that big. :wink:  

Screencast from 2023-11-08 16-20-54

**Comment by matheuscteo** [comment]
Very nitpicking: Is there any particular reason for the log dialog to have a minimum size? 
If not, I'd suggest you to change `setMinumumSize(1000, 800)` into a simple `resize(1000, 800)`. 
The effect is the same but the user can still make the dialog smaller if necessary.

**Comment by takluyver** [comment]
Good point, thanks. :+1: I think I was just looking for a `set*` method.

**Comment by matheuscteo** [comment]
Thanks, LGTM.

**Comment by takluyver** [comment]
Thanks! :slightly_smiling_face:

**Pull request merged**
