### PR TITLE
Add maximize / minimize buttons to plot dialog

### PR DESCRIPTION
**Pull request by tmichela**
widget

### CODE REVIEW

**Review by JamesWrigley — APPROVED** [review]
LGTM, though they automatically show up on all the systems I've run DAMNIT on :thinking:

**Comment by takluyver** [comment]
On XFCE it seems to have maximize but not minimize (the up arrow is the unusual 'roll up' option): 
image

Have you checked that minimize actually works? It's greyed out in the right click menu.

I presume this is all because it's subclassed from a dialog instead of a regular window.

**Comment by tmichela** [comment]
Strange, they do not show up in the HED's control room (Ubuntu 22). Also not on my desktop (also Ubuntu 22).
But it appears on fastx indeed... :thinking:

**Comment by tmichela** [comment]
> Have you checked that minimize actually works? 

yep, it works

**Comment by takluyver** [comment]
LGTM, then.

**Pull request merged**
